### ISSUE TITLE
Vim plugin - dj and dk behave incorrectly

### ISSUE THREAD

**Issue by TamaMcGlinn** [AdaCore/gnatstudio#36]
In vim, dj and dk deletes the current line entirely, and the line either below or above, respectively.

In GPS with the vim plugin, it is treated as a command to delete forwards or backwards until the character above or below the cursor, which is something entirely different.

**Comment by AnthonyLeonardoGracio** [comment]
Hello,

Thanks for reporting that issue, we'll have a look.

**Comment by TamaHobbit** [comment]
Similarly, cj and ck should modify the current line and the line above/below.

The best way to solve these issues would be to delegate the functionality to an embedded [NeoVim](https://neovim.io/).

**Comment by AnthonyLeonardoGracio** [comment]
Indeed. As you have seen, the Vim plugin is almost obsolete and this is not an high priority for us.

One thing you can try is to fix the vim plugin by your own, and we can help you with that. The vim plugin is located under $GPS_INSTALL/share/gps/library/vim.py.

Embed NeoVim might also be a good solution but unfortunately we won't have time to do that any time soon.

Note that in parallel we are actively working on the Ada Language Server, which will hopefully allow users to choose their favorite editor/IDE to develop in Ada, as long as this editor/IDE implements the Microsoft Language Server Protocol (see https://github.com/AdaCore/ada_language_server for more details). And the good news is that Neovim supports this protocol.

I will close the other issues you opened on Vim since we will probably never have time to work on it. Again, feel free to try to fix it by yourself and propose a merge request, if you have the time for that of course :)

Regards,
