### ISSUE TITLE
Theming completely breaks on theme change

### ISSUE THREAD

**Issue by Entomy** [AdaCore/gnatstudio#85]
![image](https://user-images.githubusercontent.com/25399505/61127361-0ef03000-a47d-11e9-9046-dd40fc9200ed.png)

![image](https://user-images.githubusercontent.com/25399505/61127371-19aac500-a47d-11e9-8fa6-3aa4f6fb07f7.png)

Occured on:
Ubuntu 18.04 x86_64
GPS 20190106

Steps to reproduce:
Set up with default settings, and the Adwaita Dark theme.
Open default project.
Change to Adwaita Light theme.

**Comment by setton** [comment]
Ah indeed! That's an oversight on our part, we should remove the entry that allows switching manually between Adwaita and Adwaita Dark! 

You should be able to switch themes via the General/Color Theme section now.

**Comment by david-tamar** [comment]
> Ah indeed! That's an oversight on our part, we should remove the entry that allows switching manually between Adwaita and Adwaita Dark!
> 
> You should be able to switch themes via the General/Color Theme section now.

What do you mean remove the entry that allows to change to Adwaita Dark?
You mean disabling GTK theme switching at all? Then how are we going to apply our GTK themes over GPS to keep the native look & feel with the rest of our system on Linux desktops?

**Comment by david-tamar** [comment]
Update: It appears that deleting everything from the the `gps.css` has improved my user experience greatly with GPS on Linux Debian. It just let the GTK theme do its job.

You may also want to look forward into the file and modify it since there's a lot of access to many GPS-specific classes instead of just deleting everything from there. On Debian the file is located at `/usr/share/gps/gps.css`.

You can also inspect and debug the GTK layout of GPS on the fly and find out all of the CSS classes via the GTK inspector by launching GPS from a command line shell with `GTK_DEBUG=interactive gnat-gps` (works on Debian).

**Comment by AnthonyLeonardoGracio** [comment]
> > Ah indeed! That's an oversight on our part, we should remove the entry that allows switching manually between Adwaita and Adwaita Dark!
> > You should be able to switch themes via the General/Color Theme section now.
> 
> What do you mean remove the entry that allows to change to Adwaita Dark?
> You mean disabling GTK theme switching at all? Then how are we going to apply our GTK themes over GPS to keep the native look & feel with the rest of our system on Linux desktops?

No, users will still be able to switch themes via the Color Themes page in the Preferences dialog. We are just talking about removing the 'Theme' preference in the Custom Styles page.

Regards,

**Comment by david-tamar** [comment]
@AnthonyLeonardoGracio, the «Theme» preference in «Custom Styles» allows to switch between different GTK stylesheets (i.e. Adwaita). If you will remove that entry, Linux users (on either Debian or Fedora) will not be able to switch the GTK stylesheet to match their own environment's look & feel.

When GPS launched on my Debian system in the first time, it did not respect my system-wide setting for GTK theme. I had to set the «Theme» entry manually that you want to remove. That is an important factor for all *nix cultures. We don't like using programs that look out of place and disobey our system settings. This is why Electron-based programs and Java GUIs suffer a great penalty and negative opinion among conservative Debian and Arch users. GPS is already based on GTK, so why not just respect the system settings from gsettings or xsettings? Many Linux users also make their own stylesheets for GTK, it's very common because we have a strong Do-It-Yourself culture.
